build1: threadquesone.c
	gcc threadquesone.c

build2: threadquestwo.c
	gcc threadquestwo.c


build3: threadquesthree.c
	gcc threadquesthree.c



run1: 
	./a.out

run2:
	./a.out

run3:
	./a.out

