Project_Name = Assignment

SRC = mystring.c\
	myutlibs.c\
	test.c\
	bit_setReset.c

$(Project_Name).out: $(SRC) 
	gcc $^ -o  $@ 

run:
	./$(Project_Name).out

clean:
	rm -rf *.o *.out

